'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,Circle,FolderCheck,CalendarDays,UserRound,Gauge} from 'lucide-react';

type ActionDef={title:string;desc:string;time:string;proof:string;impact:string;owner:string};
const catalog:Record<string,ActionDef[]>={
'Stratégie & gouvernance':[
 {title:'Formaliser une politique RSE',desc:'Rédiger une politique courte avec engagements, responsabilités et objectifs.',time:'2 h',proof:'Politique RSE signée',impact:'Fort',owner:'Direction'},
 {title:'Nommer un pilote RSE',desc:'Désigner la personne responsable du suivi de la démarche.',time:'30 min',proof:'Lettre de mission',impact:'Fort',owner:'Direction'},
 {title:'Installer une revue RSE trimestrielle',desc:'Définir les indicateurs et le rituel de pilotage à partager avec la direction.',time:'1 h',proof:'Tableau de bord + compte rendu',impact:'Moyen',owner:'Pilote RSE'}],
'Environnement':[
 {title:'Choisir 3 indicateurs environnementaux',desc:'Commencer par les consommations et impacts les plus matériels pour votre activité.',time:'1 h',proof:'Tableau d’indicateurs',impact:'Fort',owner:'Pilote RSE'},
 {title:'Définir une première action de réduction',desc:'Fixer une action mesurable à réaliser dans les 90 jours.',time:'1 h',proof:'Fiche action chiffrée',impact:'Fort',owner:'Opérations'},
 {title:'Mesurer le premier résultat',desc:'Comparer la situation initiale au résultat obtenu et documenter l’écart.',time:'1 h',proof:'Relevé avant/après',impact:'Moyen',owner:'Opérations'}],
'Social & conditions de travail':[
 {title:'Formaliser les actions sociales prioritaires',desc:'Identifier santé, sécurité, compétences et conditions de travail à traiter.',time:'2 h',proof:'Plan social RSE',impact:'Fort',owner:'Direction / RH'},
 {title:'Choisir un indicateur social',desc:'Suivre un indicateur simple et utile à la direction.',time:'45 min',proof:'Tableau de suivi',impact:'Moyen',owner:'Direction / RH'},
 {title:'Faire un point collaborateurs',desc:'Recueillir un retour court sur le sujet social prioritaire et décider d’une amélioration.',time:'2 h',proof:'Synthèse + action décidée',impact:'Fort',owner:'Manager'}],
'Achats responsables':[
 {title:'Créer une charte fournisseurs responsables',desc:'Formaliser les attentes sociales, environnementales et éthiques.',time:'3 h',proof:'Charte fournisseurs',impact:'Fort',owner:'Achats / Direction'},
 {title:'Intégrer un critère RSE aux consultations',desc:'Ajouter au moins un critère RSE dans les prochains achats significatifs.',time:'1 h',proof:'Grille de consultation',impact:'Fort',owner:'Achats'},
 {title:'Évaluer 3 fournisseurs stratégiques',desc:'Tester une grille courte sur les fournisseurs les plus importants ou exposés.',time:'2 h',proof:'Évaluations fournisseurs',impact:'Fort',owner:'Achats'}],
'Ancrage territorial':[
 {title:'Cartographier les parties prenantes locales',desc:'Lister acteurs, réseaux, associations et partenaires importants.',time:'1 h',proof:'Cartographie parties prenantes',impact:'Moyen',owner:'Direction'},
 {title:'Choisir une action territoriale',desc:'Sélectionner une contribution cohérente avec l’activité de l’entreprise.',time:'1 h',proof:'Fiche action',impact:'Moyen',owner:'Pilote RSE'},
 {title:'Mesurer la contribution locale',desc:'Identifier un indicateur : achats locaux, emplois, partenariats ou heures engagées.',time:'1 h',proof:'Indicateur territorial',impact:'Moyen',owner:'Pilote RSE'}],
'Clients & marché':[
 {title:'Créer un dossier de preuves RSE client',desc:'Regrouper les documents les plus souvent demandés par les clients.',time:'2 h',proof:'Dossier preuves client',impact:'Très fort',owner:'Direction / Commerce'},
 {title:'Lister les exigences RSE des clients clés',desc:'Recenser questionnaires, clauses et demandes récurrentes.',time:'1 h',proof:'Matrice exigences clients',impact:'Très fort',owner:'Commerce'},
 {title:'Préparer une réponse RSE réutilisable',desc:'Créer une trame factuelle pour appels d’offres et questionnaires clients.',time:'2 h',proof:'Trame de réponse RSE',impact:'Fort',owner:'Commerce'}]
};
const phases=[{label:'0–30 jours',objective:'Poser les bases',day:30},{label:'31–60 jours',objective:'Mettre en œuvre',day:60},{label:'61–90 jours',objective:'Mesurer & prouver',day:90}];
export default function Actions(){const[priorities,setPriorities]=useState<string[]>([]);const[done,setDone]=useState<string[]>([]);useEffect(()=>{try{const d=JSON.parse(localStorage.getItem('fabrique-impact-diagnostic')||'{}');setPriorities(d.priorities||Object.keys(catalog).slice(0,3));setDone(JSON.parse(localStorage.getItem('fabrique-impact-actions')||'[]'))}catch{}},[]);function toggle(id:string){const n=done.includes(id)?done.filter(x=>x!==id):[...done,id];setDone(n);localStorage.setItem('fabrique-impact-actions',JSON.stringify(n))}const actions=priorities.flatMap((pillar,pIndex)=>(catalog[pillar]||[]).map((a,i)=>({id:`${pillar}-${i}`,pillar,priority:pIndex+1,phase:i,...a})));const completed=actions.filter(a=>done.includes(a.id)).length;return <main className="actionPage"><div className="actionWrap"><Link href="/dashboard/" className="backLink"><ArrowLeft/> Tableau de bord</Link><span className="kicker">VOTRE FEUILLE DE ROUTE</span><h1>Votre plan d’action RSE sur 90 jours.</h1><p className="actionLead">9 actions issues de vos 3 priorités. Avancez dans l’ordre, désignez le bon responsable et conservez la preuve de chaque progrès.</p><div className="actionProgress"><div><b>{completed}</b><span>actions réalisées</span></div><div><b>{actions.length-completed}</b><span>à réaliser</span></div><div><b>{actions.length?Math.round(completed/actions.length*100):0}%</b><span>progression du plan</span></div></div><div className="roadmapPhases">{phases.map((phase,phaseIndex)=>{const phaseActions=actions.filter(a=>a.phase===phaseIndex);return <section key={phase.label} className="roadmapPhase"><header><div className="phaseNumber">{phaseIndex+1}</div><div><span>{phase.label}</span><h2>{phase.objective}</h2></div><small>{phaseActions.filter(a=>done.includes(a.id)).length}/{phaseActions.length} réalisées</small></header><div className="actionList">{phaseActions.map(a=><article className={done.includes(a.id)?'done':''} key={a.id}><button className="checkAction" onClick={()=>toggle(a.id)} aria-label="Marquer comme réalisée">{done.includes(a.id)?<CheckCircle2/>:<Circle/>}</button><div><div className="actionTags"><span className="actionPillar">PRIORITÉ {a.priority} · {a.pillar}</span><span className="impactTag"><Gauge/>Impact {a.impact}</span></div><h3>{a.title}</h3><p>{a.desc}</p><div className="actionMeta"><span>⏱ {a.time}</span><span><UserRound/> {a.owner}</span><span><CalendarDays/> avant J+{phases[a.phase].day}</span><span><FolderCheck/> {a.proof}</span></div></div><Link className="proofButton" href="/proofs/">Ajouter une preuve</Link></article>)}</div></section>})}</div><div className="nextStep"><div><span className="kicker">LA BOUCLE DE PROGRÈS</span><h2>Une action terminée ? Transformez-la en preuve.</h2><p className="actionLead">Votre coffre RSE centralise ce qui pourra être valorisé auprès de vos clients et partenaires.</p></div><Link className="button" href="/proofs/">Ouvrir mon coffre de preuves →</Link></div></div></main>}
