import type { MsdgCatalogTemplate } from './msdgRseCatalog';
import type { SourceCatalogItem } from './sourceCatalog';

function layoutFor(type:string):MsdgCatalogTemplate['layout']{
  if(type==='Plan')return'ACTION_PLAN';
  if(['Registre','Matrice','Reporting'].includes(type))return'REGISTER';
  if(['Analyse','Questionnaire','Checklist'].includes(type))return'ASSESSMENT';
  if(type==='Preuve')return'PROOF';
  if(['Rapport','Compte rendu','Fiche'].includes(type))return'REPORT';
  return'POLICY';
}

const identity=(source:SourceCatalogItem)=>`# ${source.title}\n\n**Entreprise :** {{nom_entreprise}}  \n**Référence catalogue :** ${source.id}  \n**Catégorie :** ${source.category}  \n**Type :** ${source.type}  \n**Priorité :** ${source.priority}  \n**Version :** {{version}}  \n**Date :** {{date}}  \n**Responsable :** {{responsable}}`;

const summary=(source:SourceCatalogItem)=>`## Synthèse exécutive\n\n### Finalité\n{{objet}}\n\n### Pourquoi ce document est utile maintenant\n{{enjeux}}\n\n### Périmètre\n{{perimetre}}\n\n### 3 décisions / engagements clés\n1. {{point_1}}\n2. {{point_2}}\n3. {{point_3}}\n\n### Pilotage\n- Pilote : {{role_pilote}}\n- Échéance / période : {{echeance}}\n- Fréquence de revue : {{frequence_revue}}\n- Validation : {{validateur}}\n\n### Preuves clés\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}`;

const policy=(source:SourceCatalogItem)=>`${identity(source)}\n\n${summary(source)}\n\n## 1. Objet et finalité\n${source.title} constitue le cadre de référence de {{nom_entreprise}} pour le sujet concerné. Le document précise les engagements, règles de décision, responsabilités, modalités de mise en œuvre et preuves attendues.\n\n{{contenu_principal}}\n\n## 2. Périmètre d’application\n{{perimetre}}\n\n### Activités, sites et personnes concernées\n{{entites_concernees}}\n\n### Situations hors périmètre ou nécessitant une adaptation\n{{exceptions_perimetre}}\n\n## 3. Contexte, enjeux, risques et opportunités\n{{enjeux}}\n\n{{risques_impacts}}\n\n### Parties prenantes concernées\n{{parties_prenantes}}\n\n## 4. Principes directeurs\n1. {{engagement_1}}\n2. {{engagement_2}}\n3. {{engagement_3}}\n4. {{engagement_4}}\n\n### Principes complémentaires propres à l’entreprise\n{{principes_complementaires}}\n\n## 5. Règles et exigences opérationnelles\n{{regles_operationnelles}}\n\n### Points de vigilance\n{{points_vigilance}}\n\n### Critères de décision ou d’escalade\n{{criteres_escalade}}\n\n## 6. Rôles et responsabilités\n- Direction : {{role_direction}}\n- Pilote : {{role_pilote}}\n- Managers / responsables opérationnels : {{role_managers}}\n- Collaborateurs / contributeurs : {{role_autres}}\n\n## 7. Déploiement\n{{deploiement}}\n\n### Sensibilisation / communication\n{{communication_politique}}\n\n### Outils et documents associés\n{{outils_associes}}\n\n## 8. Objectifs et indicateurs\n| Objectif | Indicateur | Valeur de départ | Cible | Échéance | Responsable |\n|---|---|---|---|---|---|\n| {{objectif_1}} | {{kpi_1}} | {{baseline_1}} | {{cible_1}} | {{echeance_1}} | {{responsable_1}} |\n| {{objectif_2}} | {{kpi_2}} | {{baseline_2}} | {{cible_2}} | {{echeance_2}} | {{responsable_2}} |\n| {{objectif_3}} | {{kpi_3}} | {{baseline_3}} | {{cible_3}} | {{echeance_3}} | {{responsable_3}} |\n\n## 9. Preuves et traçabilité\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n- {{preuve_4}}\n\n### Modalités d’archivage\n{{modalites_archivage}}\n\n## 10. Gestion des écarts\n{{processus_ecarts}}\n\n## 11. Révision et amélioration continue\n{{modalites_revue}}\n\n### Prochaine amélioration prioritaire\n{{prochaine_amelioration}}\n\n## Validation\n- Validateur : {{validateur}}\n- Date de validation : {{date_validation}}\n- Statut : {{statut_validation}}\n- Commentaires / décisions : {{commentaires_validation}}`;

const actionPlan=(source:SourceCatalogItem)=>`${identity(source)}\n\n${summary(source)}\n\n## 1. Objectif du plan\n{{objectif_global}}\n\n## 2. Situation de départ\n{{diagnostic_initial}}\n\n## 3. Périmètre et parties prenantes\n{{perimetre}}\n\n{{parties_prenantes}}\n\n## 4. Résultats attendus\n{{resultats_attendus}}\n\n## 5. Plan d’actions détaillé\n| ID | Action | Priorité | Responsable | Début | Échéance | Moyens / budget | KPI | Cible | Statut | Preuve |\n|---|---|---|---|---|---|---|---|---|---|---|\n| A01 | {{action_1}} | {{priorite_1}} | {{responsable_1}} | {{debut_1}} | {{echeance_1}} | {{budget_1}} | {{kpi_1}} | {{cible_1}} | {{statut_1}} | {{preuve_1}} |\n| A02 | {{action_2}} | {{priorite_2}} | {{responsable_2}} | {{debut_2}} | {{echeance_2}} | {{budget_2}} | {{kpi_2}} | {{cible_2}} | {{statut_2}} | {{preuve_2}} |\n| A03 | {{action_3}} | {{priorite_3}} | {{responsable_3}} | {{debut_3}} | {{echeance_3}} | {{budget_3}} | {{kpi_3}} | {{cible_3}} | {{statut_3}} | {{preuve_3}} |\n\n## 6. Risques et dépendances\n{{risques_dependances}}\n\n## 7. Gouvernance de suivi\n- Instance : {{instance}}\n- Fréquence : {{frequence}}\n- Règle d’escalade : {{regle_escalade}}\n\n## 8. Ressources et moyens\n{{ressources_moyens}}\n\n## 9. Communication et mobilisation\n{{communication_politique}}\n\n## 10. Preuves et livrables attendus\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 11. Bilan et décisions\n{{bilan}}\n\n## Validation\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Commentaires : {{commentaires_validation}}`;

const register=(source:SourceCatalogItem)=>`${identity(source)}\n\n${summary(source)}\n\n## 1. Objet du registre / tableau de pilotage\n{{objet}}\n\n## 2. Périmètre\n{{perimetre}}\n\n## 3. Règles de gestion\n{{regles_operationnelles}}\n\n## 4. Données à enregistrer\n| Référence | Sujet / élément | Catégorie | Responsable | Date | Statut | Niveau de risque / priorité | Action attendue | Preuve / source |\n|---|---|---|---|---|---|---|---|---|\n| {{reference_1}} | {{element_1}} | {{categorie_1}} | {{responsable_1}} | {{date_1}} | {{statut_1}} | {{niveau_1}} | {{action_1}} | {{preuve_1}} |\n| {{reference_2}} | {{element_2}} | {{categorie_2}} | {{responsable_2}} | {{date_2}} | {{statut_2}} | {{niveau_2}} | {{action_2}} | {{preuve_2}} |\n| {{reference_3}} | {{element_3}} | {{categorie_3}} | {{responsable_3}} | {{date_3}} | {{statut_3}} | {{niveau_3}} | {{action_3}} | {{preuve_3}} |\n\n## 5. Critères de classement ou de notation\n{{criteres_notation}}\n\n## 6. Modalités de mise à jour\n{{modalites_mise_a_jour}}\n\n## 7. Responsabilités\n- Propriétaire du registre : {{role_pilote}}\n- Contributeurs : {{role_autres}}\n- Validation / revue : {{validateur}}\n\n## 8. Contrôles de qualité des données\n{{controle_donnees}}\n\n## 9. Indicateurs issus du registre\n- {{kpi_1}}\n- {{kpi_2}}\n- {{kpi_3}}\n\n## 10. Archivage et preuve\n{{modalites_archivage}}\n\n## 11. Revue périodique\n{{modalites_revue}}`;

const assessment=(source:SourceCatalogItem)=>`${identity(source)}\n\n${summary(source)}\n\n## 1. Objectif de l’évaluation\n{{objet}}\n\n## 2. Périmètre et méthode\n{{perimetre}}\n\n{{methode_evaluation}}\n\n## 3. Sources et données utilisées\n{{sources_donnees}}\n\n## 4. Critères d’analyse\n| Critère | Question / test | Méthode | Niveau attendu | Résultat | Preuve |\n|---|---|---|---|---|---|\n| {{critere_1}} | {{question_1}} | {{methode_1}} | {{niveau_attendu_1}} | {{resultat_1}} | {{preuve_1}} |\n| {{critere_2}} | {{question_2}} | {{methode_2}} | {{niveau_attendu_2}} | {{resultat_2}} | {{preuve_2}} |\n| {{critere_3}} | {{question_3}} | {{methode_3}} | {{niveau_attendu_3}} | {{resultat_3}} | {{preuve_3}} |\n\n## 5. Constats principaux\n{{constats_principaux}}\n\n## 6. Points forts\n{{points_forts}}\n\n## 7. Écarts / risques / points de vigilance\n{{risques_impacts}}\n\n## 8. Priorisation\n{{priorisation}}\n\n## 9. Recommandations et actions\n1. {{action_1}}\n2. {{action_2}}\n3. {{action_3}}\n\n## 10. Responsabilités et échéances\n{{responsabilites_echeances}}\n\n## 11. Preuves et annexes\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 12. Validation de l’analyse\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Commentaires : {{commentaires_validation}}`;

const report=(source:SourceCatalogItem)=>`${identity(source)}\n\n${summary(source)}\n\n## 1. Objet et contexte\n{{objet}}\n\n{{enjeux}}\n\n## 2. Périmètre et période couverte\n{{perimetre}}\n\n{{periode}}\n\n## 3. Méthode et sources\n{{methode_evaluation}}\n\n{{sources_donnees}}\n\n## 4. Résultats clés\n{{resultats_cles}}\n\n## 5. Analyse détaillée\n{{contenu_principal}}\n\n## 6. Indicateurs\n| Indicateur | Valeur | Cible / référence | Évolution | Commentaire |\n|---|---|---|---|---|\n| {{kpi_1}} | {{valeur_1}} | {{cible_1}} | {{evolution_1}} | {{commentaire_1}} |\n| {{kpi_2}} | {{valeur_2}} | {{cible_2}} | {{evolution_2}} | {{commentaire_2}} |\n| {{kpi_3}} | {{valeur_3}} | {{cible_3}} | {{evolution_3}} | {{commentaire_3}} |\n\n## 7. Écarts, risques et enseignements\n{{risques_impacts}}\n\n## 8. Actions décidées\n1. {{action_1}}\n2. {{action_2}}\n3. {{action_3}}\n\n## 9. Responsables et prochaines échéances\n{{responsabilites_echeances}}\n\n## 10. Preuves et annexes\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 11. Validation / diffusion\n- Validateur : {{validateur}}\n- Public destinataire : {{destinataires}}\n- Date : {{date_validation}}`;

const proof=(source:SourceCatalogItem)=>`${identity(source)}\n\n## Synthèse de la preuve\n- Preuve originale : {{preuve_1}}\n- Sujet démontré : {{objet}}\n- Périmètre : {{perimetre}}\n- Période : {{periode}}\n- Responsable : {{responsable}}\n- Statut de vérification : {{statut_validation}}\n\n## 1. Objet de la fiche de preuve\nCette fiche référence et contextualise une pièce existante. Elle ne remplace pas le document original et ne crée pas à elle seule la conformité ou la preuve.\n\n{{objet}}\n\n## 2. Document ou élément original\n{{preuve_1}}\n\n## 3. Périmètre, période et propriétaire\n{{perimetre}}\n\n{{periode}}\n\n{{responsable}}\n\n## 4. Ce que cette preuve démontre\n{{contenu_principal}}\n\n## 5. Source, origine et traçabilité\n{{source_preuve}}\n\n## 6. Contrôles effectués\n{{controles_preuve}}\n\n## 7. Limites ou réserves\n{{limites_preuve}}\n\n## 8. Documents liés\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 9. Archivage et durée de conservation\n{{modalites_archivage}}\n\n## 10. Validation et prochaine vérification\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Prochaine vérification : {{date_prochaine_revue}}`;

export function buildEnrichedCatalogTemplate(source:SourceCatalogItem):MsdgCatalogTemplate{
  const layout=layoutFor(source.type);
  const markdown=source.model==='FICHE DE PREUVE V3'||layout==='PROOF'?proof(source):layout==='ACTION_PLAN'?actionPlan(source):layout==='REGISTER'?register(source):layout==='ASSESSMENT'?assessment(source):layout==='REPORT'?report(source):policy(source);
  return{
    id:source.id,
    title:source.title,
    category:source.category,
    type:source.type,
    priority:source.priority,
    frameworks:[],
    frequency:'Selon contexte',
    layout,
    sourcePath:`catalogue-source/${source.id}`,
    description:`Trame enrichie et personnalisable de type ${source.type.toLowerCase()} : synthèse exécutive, contenu métier détaillé, pilotage, responsabilités, indicateurs, preuves et validation.`,
    markdown,
  };
}
