import type { MsdgCatalogTemplate } from './msdgRseCatalog';
import type { SourceCatalogItem } from './sourceCatalog';

function layoutFor(type:string):MsdgCatalogTemplate['layout']{
  if(type==='Plan')return'ACTION_PLAN';
  if(['Registre','Matrice','Reporting'].includes(type))return'REGISTER';
  if(['Analyse','Questionnaire','Checklist'].includes(type))return'ASSESSMENT';
  if(type==='Preuve')return'PROOF';
  if(['Rapport','Compte rendu','Fiche'].includes(type))return'REPORT';
  return'POLICY';
}

const identity=(s:SourceCatalogItem)=>`# ${s.title}\n\n**Entreprise :** {{nom_entreprise}}  \n**Référence catalogue :** ${s.id}  \n**Catégorie :** ${s.category}  \n**Type :** ${s.type}  \n**Priorité :** ${s.priority}  \n**Version :** {{version}}  \n**Date :** {{date}}  \n**Responsable :** {{responsable}}`;
const summary=`## Synthèse exécutive\n\n### Finalité\n{{objet}}\n\n### Pourquoi ce document est utile maintenant\n{{enjeux}}\n\n### Périmètre\n{{perimetre}}\n\n### 3 décisions / engagements clés\n1. {{point_1}}\n2. {{point_2}}\n3. {{point_3}}\n\n### Pilotage\n- Pilote : {{role_pilote}}\n- Échéance / période : {{echeance}}\n- Fréquence de revue : {{frequence_revue}}\n- Validation : {{validateur}}\n\n### Preuves clés\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}`;

const premiumProfiles:Record<string,string>= {
'04-001':`## 5. Valeurs et comportements attendus\n{{valeurs_ethiques}}\n\n## 6. Intégrité des affaires\n{{integrite_affaires}}\n\n## 7. Conflits d’intérêts, cadeaux et invitations\n{{conflits_cadeaux}}\n\n## 8. Confidentialité, données et actifs de l’entreprise\n{{confidentialite_actifs}}\n\n## 9. Relations avec clients, fournisseurs et concurrents\n{{relations_affaires}}\n\n## 10. Dispositif d’alerte et protection des lanceurs d’alerte\n{{alerte_ethique}}`,
'04-003':`## 5. Principe de tolérance et situations interdites\n{{tolerance_corruption}}\n\n## 6. Cadeaux, invitations, dons et sponsoring\n{{cadeaux_invitations}}\n\n## 7. Intermédiaires, agents, apporteurs d’affaires et tiers\n{{tiers_intermediaires}}\n\n## 8. Conflits d’intérêts\n{{conflits_interets}}\n\n## 9. Due diligence et contrôles proportionnés\n{{due_diligence}}\n\n## 10. Signalement, enquête et traitement des écarts\n{{signalement_enquete}}`,
'05-001':`## 5. Engagement en faveur des droits humains\n{{engagement_droits_humains}}\n\n## 6. Travail forcé, travail des enfants et traite des personnes\n{{travail_force_enfants}}\n\n## 7. Santé, sécurité, dignité et conditions de travail\n{{sante_securite_dignite}}\n\n## 8. Non-discrimination, diversité et liberté d’association\n{{non_discrimination_liberte}}\n\n## 9. Chaîne d’approvisionnement et diligence raisonnable\n{{diligence_chaine_valeur}}\n\n## 10. Remédiation et signalement\n{{remediation_signalement}}`,
'05-013':`## 5. Exigences éthiques fournisseurs\n{{exigences_ethiques_fournisseurs}}\n\n## 6. Droits humains et conditions de travail\n{{exigences_sociales_fournisseurs}}\n\n## 7. Santé et sécurité\n{{exigences_sante_securite_fournisseurs}}\n\n## 8. Environnement et ressources\n{{exigences_environnement_fournisseurs}}\n\n## 9. Sous-traitance et chaîne d’approvisionnement\n{{sous_traitance_fournisseurs}}\n\n## 10. Évaluation, audit et plans correctifs\n{{evaluation_audit_fournisseurs}}`,
'05-014':`## 5. Nos engagements envers les fournisseurs\n{{engagements_entreprise_fournisseurs}}\n\n## 6. Engagements attendus des fournisseurs\n{{engagements_fournisseurs}}\n\n## 7. Dialogue, innovation et amélioration continue\n{{dialogue_innovation}}\n\n## 8. Équité, dépendance économique et délais de paiement\n{{equite_paiement}}\n\n## 9. Environnement, social et éthique\n{{attentes_rse_fournisseurs}}\n\n## 10. Suivi de la charte\n{{suivi_charte_fournisseurs}}`,
'06-001':`## 5. Emploi responsable et parcours collaborateur\n{{emploi_parcours}}\n\n## 6. Santé, sécurité et qualité de vie au travail\n{{qvct_sante_securite}}\n\n## 7. Compétences, formation et employabilité\n{{competences_formation}}\n\n## 8. Dialogue social et écoute des collaborateurs\n{{dialogue_social}}\n\n## 9. Diversité, égalité et inclusion\n{{diversite_inclusion}}\n\n## 10. Organisation du travail et équilibre des temps de vie\n{{organisation_travail}}`,
'06-020':`## 5. Non-discrimination et égalité de traitement\n{{non_discrimination}}\n\n## 6. Recrutement et évolution professionnelle\n{{recrutement_evolution}}\n\n## 7. Égalité professionnelle et rémunération\n{{egalite_remuneration}}\n\n## 8. Handicap et accessibilité\n{{handicap_accessibilite}}\n\n## 9. Inclusion, prévention du harcèlement et climat de travail\n{{inclusion_harcelement}}\n\n## 10. Mesure et suivi de la diversité\n{{mesure_diversite}}`
};

function policy(s:SourceCatalogItem){const premium=premiumProfiles[s.id]||`## 5. Règles et exigences opérationnelles\n{{regles_operationnelles}}\n\n### Points de vigilance\n{{points_vigilance}}\n\n### Critères de décision ou d’escalade\n{{criteres_escalade}}`;return`${identity(s)}\n\n${summary}\n\n## 1. Objet et finalité\n${s.title} constitue le cadre de référence de {{nom_entreprise}}. Il précise les engagements, responsabilités, règles d’application, objectifs, indicateurs et preuves attendues.\n\n{{contenu_principal}}\n\n## 2. Périmètre d’application\n{{perimetre}}\n\n### Activités, sites et personnes concernées\n{{entites_concernees}}\n\n### Exceptions ou adaptations\n{{exceptions_perimetre}}\n\n## 3. Contexte, enjeux, risques et opportunités\n{{enjeux}}\n\n{{risques_impacts}}\n\n### Parties prenantes concernées\n{{parties_prenantes}}\n\n## 4. Principes directeurs\n1. {{engagement_1}}\n2. {{engagement_2}}\n3. {{engagement_3}}\n4. {{engagement_4}}\n\n${premium}\n\n## 11. Rôles et responsabilités\n- Direction : {{role_direction}}\n- Pilote : {{role_pilote}}\n- Managers : {{role_managers}}\n- Collaborateurs / contributeurs : {{role_autres}}\n\n## 12. Déploiement, sensibilisation et communication\n{{deploiement}}\n\n{{communication_politique}}\n\n### Outils et documents associés\n{{outils_associes}}\n\n## 13. Objectifs et indicateurs\n| Objectif | Indicateur | Valeur de départ | Cible | Échéance | Responsable |\n|---|---|---|---|---|---|\n| {{objectif_1}} | {{kpi_1}} | {{baseline_1}} | {{cible_1}} | {{echeance_1}} | {{responsable_1}} |\n| {{objectif_2}} | {{kpi_2}} | {{baseline_2}} | {{cible_2}} | {{echeance_2}} | {{responsable_2}} |\n| {{objectif_3}} | {{kpi_3}} | {{baseline_3}} | {{cible_3}} | {{echeance_3}} | {{responsable_3}} |\n\n## 14. Preuves et traçabilité\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n- {{preuve_4}}\n\n### Archivage\n{{modalites_archivage}}\n\n## 15. Gestion des écarts\n{{processus_ecarts}}\n\n## 16. Révision et amélioration continue\n{{modalites_revue}}\n\n### Prochaine amélioration prioritaire\n{{prochaine_amelioration}}\n\n## Validation\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Statut : {{statut_validation}}\n- Commentaires : {{commentaires_validation}}`;}

function actionPlan(s:SourceCatalogItem){return`${identity(s)}\n\n${summary}\n\n## 1. Objectif du plan\n{{objectif_global}}\n\n## 2. Situation de départ\n{{diagnostic_initial}}\n\n## 3. Périmètre et parties prenantes\n{{perimetre}}\n\n{{parties_prenantes}}\n\n## 4. Résultats attendus\n{{resultats_attendus}}\n\n## 5. Plan d’actions détaillé\n| ID | Action | Priorité | Responsable | Début | Échéance | Moyens / budget | KPI | Cible | Statut | Preuve |\n|---|---|---|---|---|---|---|---|---|---|---|\n| A01 | {{action_1}} | {{priorite_1}} | {{responsable_1}} | {{debut_1}} | {{echeance_1}} | {{budget_1}} | {{kpi_1}} | {{cible_1}} | {{statut_1}} | {{preuve_1}} |\n| A02 | {{action_2}} | {{priorite_2}} | {{responsable_2}} | {{debut_2}} | {{echeance_2}} | {{budget_2}} | {{kpi_2}} | {{cible_2}} | {{statut_2}} | {{preuve_2}} |\n| A03 | {{action_3}} | {{priorite_3}} | {{responsable_3}} | {{debut_3}} | {{echeance_3}} | {{budget_3}} | {{kpi_3}} | {{cible_3}} | {{statut_3}} | {{preuve_3}} |\n\n## 6. Risques et dépendances\n{{risques_dependances}}\n\n## 7. Gouvernance de suivi\n- Instance : {{instance}}\n- Fréquence : {{frequence}}\n- Escalade : {{regle_escalade}}\n\n## 8. Ressources et moyens\n{{ressources_moyens}}\n\n## 9. Communication et mobilisation\n{{communication_politique}}\n\n## 10. Preuves et livrables attendus\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 11. Bilan et décisions\n{{bilan}}\n\n## Validation\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Commentaires : {{commentaires_validation}}`;}

function register(s:SourceCatalogItem){return`${identity(s)}\n\n${summary}\n\n## 1. Objet du registre / tableau de pilotage\n{{objet}}\n\n## 2. Périmètre\n{{perimetre}}\n\n## 3. Règles de gestion\n{{regles_operationnelles}}\n\n## 4. Données à enregistrer\n| Référence | Sujet / élément | Catégorie | Responsable | Date | Statut | Niveau de risque / priorité | Action attendue | Preuve / source |\n|---|---|---|---|---|---|---|---|---|\n| {{reference_1}} | {{element_1}} | {{categorie_1}} | {{responsable_1}} | {{date_1}} | {{statut_1}} | {{niveau_1}} | {{action_1}} | {{preuve_1}} |\n| {{reference_2}} | {{element_2}} | {{categorie_2}} | {{responsable_2}} | {{date_2}} | {{statut_2}} | {{niveau_2}} | {{action_2}} | {{preuve_2}} |\n| {{reference_3}} | {{element_3}} | {{categorie_3}} | {{responsable_3}} | {{date_3}} | {{statut_3}} | {{niveau_3}} | {{action_3}} | {{preuve_3}} |\n\n## 5. Critères de classement / notation\n{{criteres_notation}}\n\n## 6. Modalités de mise à jour\n{{modalites_mise_a_jour}}\n\n## 7. Responsabilités\n- Propriétaire : {{role_pilote}}\n- Contributeurs : {{role_autres}}\n- Validation : {{validateur}}\n\n## 8. Contrôle de la qualité des données\n{{controle_donnees}}\n\n## 9. Indicateurs issus du registre\n- {{kpi_1}}\n- {{kpi_2}}\n- {{kpi_3}}\n\n## 10. Archivage et preuve\n{{modalites_archivage}}\n\n## 11. Revue périodique\n{{modalites_revue}}`;}

function assessment(s:SourceCatalogItem){return`${identity(s)}\n\n${summary}\n\n## 1. Objectif de l’évaluation\n{{objet}}\n\n## 2. Périmètre et méthode\n{{perimetre}}\n\n{{methode_evaluation}}\n\n## 3. Sources et données utilisées\n{{sources_donnees}}\n\n## 4. Critères d’analyse\n| Critère | Question / test | Méthode | Niveau attendu | Résultat | Preuve |\n|---|---|---|---|---|---|\n| {{critere_1}} | {{question_1}} | {{methode_1}} | {{niveau_attendu_1}} | {{resultat_1}} | {{preuve_1}} |\n| {{critere_2}} | {{question_2}} | {{methode_2}} | {{niveau_attendu_2}} | {{resultat_2}} | {{preuve_2}} |\n| {{critere_3}} | {{question_3}} | {{methode_3}} | {{niveau_attendu_3}} | {{resultat_3}} | {{preuve_3}} |\n\n## 5. Constats principaux\n{{constats_principaux}}\n\n## 6. Points forts\n{{points_forts}}\n\n## 7. Écarts / risques / vigilance\n{{risques_impacts}}\n\n## 8. Priorisation\n{{priorisation}}\n\n## 9. Recommandations et actions\n1. {{action_1}}\n2. {{action_2}}\n3. {{action_3}}\n\n## 10. Responsabilités et échéances\n{{responsabilites_echeances}}\n\n## 11. Preuves et annexes\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 12. Validation\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Commentaires : {{commentaires_validation}}`;}

function report(s:SourceCatalogItem){return`${identity(s)}\n\n${summary}\n\n## 1. Objet et contexte\n{{objet}}\n\n{{enjeux}}\n\n## 2. Périmètre et période couverte\n{{perimetre}}\n\n{{periode}}\n\n## 3. Méthode et sources\n{{methode_evaluation}}\n\n{{sources_donnees}}\n\n## 4. Résultats clés\n{{resultats_cles}}\n\n## 5. Analyse détaillée\n{{contenu_principal}}\n\n## 6. Indicateurs\n| Indicateur | Valeur | Cible / référence | Évolution | Commentaire |\n|---|---|---|---|---|\n| {{kpi_1}} | {{valeur_1}} | {{cible_1}} | {{evolution_1}} | {{commentaire_1}} |\n| {{kpi_2}} | {{valeur_2}} | {{cible_2}} | {{evolution_2}} | {{commentaire_2}} |\n| {{kpi_3}} | {{valeur_3}} | {{cible_3}} | {{evolution_3}} | {{commentaire_3}} |\n\n## 7. Écarts, risques et enseignements\n{{risques_impacts}}\n\n## 8. Actions décidées\n1. {{action_1}}\n2. {{action_2}}\n3. {{action_3}}\n\n## 9. Responsables et prochaines échéances\n{{responsabilites_echeances}}\n\n## 10. Preuves et annexes\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 11. Validation / diffusion\n- Validateur : {{validateur}}\n- Destinataires : {{destinataires}}\n- Date : {{date_validation}}`;}

function proof(s:SourceCatalogItem){return`${identity(s)}\n\n## Synthèse de la preuve\n- Preuve originale : {{preuve_1}}\n- Sujet démontré : {{objet}}\n- Périmètre : {{perimetre}}\n- Période : {{periode}}\n- Responsable : {{responsable}}\n- Statut : {{statut_validation}}\n\n## 1. Objet de la fiche de preuve\nCette fiche référence et contextualise une pièce existante. Elle ne remplace pas le document original.\n\n{{objet}}\n\n## 2. Document original\n{{preuve_1}}\n\n## 3. Périmètre, période et propriétaire\n{{perimetre}}\n\n{{periode}}\n\n{{responsable}}\n\n## 4. Ce que la preuve démontre\n{{contenu_principal}}\n\n## 5. Source et traçabilité\n{{source_preuve}}\n\n## 6. Contrôles effectués\n{{controles_preuve}}\n\n## 7. Limites ou réserves\n{{limites_preuve}}\n\n## 8. Documents liés\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 9. Archivage\n{{modalites_archivage}}\n\n## 10. Validation et prochaine vérification\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Prochaine vérification : {{date_prochaine_revue}}`;}

export function buildEnrichedCatalogTemplate(source:SourceCatalogItem):MsdgCatalogTemplate{
  const layout=layoutFor(source.type);
  const markdown=source.model==='FICHE DE PREUVE V3'||layout==='PROOF'?proof(source):layout==='ACTION_PLAN'?actionPlan(source):layout==='REGISTER'?register(source):layout==='ASSESSMENT'?assessment(source):layout==='REPORT'?report(source):policy(source);
  return{ id:source.id,title:source.title,category:source.category,type:source.type,priority:source.priority,frameworks:[],frequency:'Selon contexte',layout,sourcePath:`catalogue-source/${source.id}`,description:`Trame enrichie et personnalisable de type ${source.type.toLowerCase()} : synthèse exécutive, contenu métier détaillé, pilotage, responsabilités, indicateurs, preuves et validation.`,markdown };
}
