import type { MsdgCatalogTemplate } from './msdgRseCatalog';
import type { SourceCatalogItem } from './sourceCatalog';

function layoutFor(type:string):MsdgCatalogTemplate['layout']{
  if(type==='Plan')return'ACTION_PLAN';
  if(['Registre','Matrice','Reporting'].includes(type))return'REGISTER';
  if(['Analyse','Questionnaire','Checklist'].includes(type))return'ASSESSMENT';
  if(type==='Preuve')return'PROOF';
  if(['Rapport','Compte rendu','Fiche'].includes(type))return'REPORT';
  return'POLICY';
}

const identity=(s:SourceCatalogItem)=>`# ${s.title}\n\n**Entreprise :** {{nom_entreprise}}  \n**Référence catalogue :** ${s.id}  \n**Catégorie :** ${s.category}  \n**Type :** ${s.type}  \n**Priorité :** ${s.priority}  \n**Version :** {{version}}  \n**Date :** {{date}}  \n**Responsable :** {{responsable}}`;

const summary=`## Synthèse exécutive\n\n### Finalité\n{{objet}}\n\n### Pourquoi ce document est utile maintenant\n{{enjeux}}\n\n### Périmètre\n{{perimetre}}\n\n### 3 décisions / engagements clés\n1. {{point_1}}\n2. {{point_2}}\n3. {{point_3}}\n\n### Pilotage\n- Pilote : {{role_pilote}}\n- Échéance / période : {{echeance}}\n- Fréquence de revue : {{frequence_revue}}\n- Validation : {{validateur}}\n\n### Preuves clés\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}`;

type DomainProfile={titles:string[];fields:string[]};
const domainProfiles:Record<string,DomainProfile>={
 '01':{titles:['Identité juridique et organisationnelle','Activités, produits et services','Implantations et périmètre','Effectifs et données économiques','Obligations, certifications et labels','Fiabilité et mise à jour des données'],fields:['identite_juridique','activites_produits','implantations_perimetre','effectifs_donnees','obligations_certifications','fiabilite_donnees']},
 '02':{titles:['Vision et ambition RSE','Gouvernance et responsabilités','Enjeux stratégiques prioritaires','Objectifs, moyens et budget','Pilotage et revues de direction','Amélioration continue'],fields:['vision_rse','gouvernance_rse','enjeux_strategiques','objectifs_moyens','revue_direction','amelioration_continue']},
 '03':{titles:['Identification des parties prenantes','Attentes et influence','Dialogue et consultation','Impacts, risques et opportunités','Matérialité et priorisation','Décisions et réponses apportées'],fields:['identification_parties_prenantes','attentes_influence','dialogue_consultation','impacts_risques_opportunites','materialite_priorisation','reponses_enjeux']},
 '04':{titles:['Intégrité et comportements attendus','Corruption, fraude et conflits d’intérêts','Cadeaux, invitations et avantages','Concurrence loyale et pratiques commerciales','Due diligence des tiers et traçabilité','Alerte, enquête et remédiation'],fields:['integrite_comportements','corruption_fraude_conflits','cadeaux_invitations','concurrence_pratiques','due_diligence_tiers','alerte_enquete_remediation']},
 '05':{titles:['Droits humains et conditions de travail','Achats responsables et coût global','Sélection, évaluation et risques fournisseurs','Exigences environnementales et sociales','Relation fournisseur, dépendance et paiement','Audit, plans correctifs et preuves'],fields:['droits_humains_travail','achats_cout_global','evaluation_risques_fournisseurs','exigences_esg_fournisseurs','relation_paiement_fournisseurs','audit_correctifs_fournisseurs']},
 '06':{titles:['Emploi et parcours collaborateur','Rémunération et équité','Dialogue social et engagement','Diversité, égalité et inclusion','Compétences et employabilité','Organisation du travail et qualité de vie'],fields:['emploi_parcours','remuneration_equite','dialogue_engagement','diversite_inclusion','competences_employabilite','organisation_qvct']},
 '07':{titles:['Identification des risques professionnels','Prévention et moyens de maîtrise','Accidents, incidents et causes racines','Habilitations, EPI et contrôles périodiques','Urgence, entreprises extérieures et continuité','RPS, QVCT et culture de prévention'],fields:['risques_professionnels','prevention_maitrise','accidents_causes','habilitations_epi','urgence_exterieurs','rps_qvct']},
 '08':{titles:['Aspects et impacts environnementaux','Émissions GES et trajectoire climat','Énergie et sobriété','Mobilité et transport','Conformité et incidents environnementaux','Plan de transition et résultats'],fields:['aspects_impacts_env','ges_trajectoire','energie_sobriete','mobilite_transport','conformite_incidents_env','transition_resultats']},
 '09':{titles:['Eau et rejets','Déchets et déchets dangereux','Matières et économie circulaire','Produits chimiques et pollution','Écoconception et cycle de vie','Biodiversité, impacts et dépendances'],fields:['eau_rejets','dechets_dangereux','matieres_circularite','chimie_pollution','ecoconception_cycle_vie','biodiversite_dependances']},
 '10':{titles:['Satisfaction, écoute et réclamations clients','Santé et sécurité des consommateurs','Marketing et allégations responsables','Accessibilité des produits et services','Engagement territorial et partenariats','Mesure de l’impact local'],fields:['satisfaction_reclamations','securite_consommateurs','marketing_allegations','accessibilite_services','engagement_territorial','impact_local']},
 '11':{titles:['Protection des données personnelles','Sécurité de l’information et accès','Incidents, continuité et reprise','Numérique responsable','Usages IA autorisés et interdits','Risques IA, validation et gouvernance'],fields:['protection_donnees','securite_information','incidents_continuite','numerique_responsable','usages_ia','risques_gouvernance_ia']},
 '12':{titles:['Référentiel des indicateurs et méthodes','Qualité, traçabilité et consolidation des données','Reporting et communication des résultats','Audit interne et contrôles','Non-conformités et actions correctives','Correspondance référentiels et amélioration'],fields:['referentiel_kpi','qualite_donnees_reporting','reporting_resultats','audit_controles','non_conformites_correctifs','correspondance_amelioration']},
 '13':{titles:['Identification de la preuve originale','Périmètre couvert par la certification ou preuve','Émetteur, date et période de validité','Ce que la preuve démontre réellement','Limites, exclusions et réserves','Vérification, archivage et renouvellement'],fields:['preuve_originale','perimetre_preuve','emetteur_validite','demonstration_preuve','limites_reserves','verification_renouvellement']},
 '14':{titles:['Exigences du référentiel visé','Périmètre et niveau d’applicabilité','Éléments de preuve attendus','Écarts et niveau de préparation','Plan de mise en conformité / progrès','Contrôle final et préparation à l’évaluation'],fields:['exigences_referentiel','applicabilite_referentiel','preuves_referentiel','ecarts_preparation','plan_progres_referentiel','controle_final_referentiel']}
};

function domainBlock(s:SourceCatalogItem,start=5){const profile=domainProfiles[s.id.slice(0,2)]||domainProfiles['02'];return profile.titles.map((title,i)=>`## ${start+i}. ${title}\n{{${profile.fields[i]}}}`).join('\n\n');}

function governance(start:number){return`## ${start}. Rôles et responsabilités\n- Direction : {{role_direction}}\n- Pilote : {{role_pilote}}\n- Managers / responsables opérationnels : {{role_managers}}\n- Collaborateurs / contributeurs : {{role_autres}}\n\n## ${start+1}. Déploiement, sensibilisation et communication\n{{deploiement}}\n\n{{communication_politique}}\n\n### Outils et documents associés\n{{outils_associes}}\n\n## ${start+2}. Objectifs et indicateurs\n| Objectif | Indicateur | Valeur de départ | Cible | Échéance | Responsable |\n|---|---|---|---|---|---|\n| {{objectif_1}} | {{kpi_1}} | {{baseline_1}} | {{cible_1}} | {{echeance_1}} | {{responsable_1}} |\n| {{objectif_2}} | {{kpi_2}} | {{baseline_2}} | {{cible_2}} | {{echeance_2}} | {{responsable_2}} |\n| {{objectif_3}} | {{kpi_3}} | {{baseline_3}} | {{cible_3}} | {{echeance_3}} | {{responsable_3}} |\n\n## ${start+3}. Preuves et traçabilité\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n- {{preuve_4}}\n\n### Archivage\n{{modalites_archivage}}\n\n## ${start+4}. Gestion des écarts et actions correctives\n{{processus_ecarts}}\n\n## ${start+5}. Révision et amélioration continue\n{{modalites_revue}}\n\n### Prochaine amélioration prioritaire\n{{prochaine_amelioration}}\n\n## Validation\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Statut : {{statut_validation}}\n- Commentaires : {{commentaires_validation}}`;}

function policy(s:SourceCatalogItem){return`${identity(s)}\n\n${summary}\n\n## 1. Objet et finalité\n${s.title} constitue le cadre de référence de {{nom_entreprise}}. Il précise les engagements, responsabilités, règles d’application, objectifs, indicateurs et preuves attendues.\n\n{{contenu_principal}}\n\n## 2. Périmètre d’application\n{{perimetre}}\n\n### Activités, sites et personnes concernées\n{{entites_concernees}}\n\n### Exceptions ou adaptations\n{{exceptions_perimetre}}\n\n## 3. Contexte, enjeux, risques et opportunités\n{{enjeux}}\n\n{{risques_impacts}}\n\n### Parties prenantes concernées\n{{parties_prenantes}}\n\n## 4. Principes directeurs\n1. {{engagement_1}}\n2. {{engagement_2}}\n3. {{engagement_3}}\n4. {{engagement_4}}\n\n${domainBlock(s,5)}\n\n${governance(11)}`;}

function actionPlan(s:SourceCatalogItem){return`${identity(s)}\n\n${summary}\n\n## 1. Objectif du plan\n{{objectif_global}}\n\n## 2. Situation de départ\n{{diagnostic_initial}}\n\n## 3. Périmètre et parties prenantes\n{{perimetre}}\n\n{{parties_prenantes}}\n\n## 4. Résultats attendus\n{{resultats_attendus}}\n\n${domainBlock(s,5)}\n\n## 11. Plan d’actions détaillé\n| ID | Action | Priorité | Responsable | Début | Échéance | Moyens / budget | KPI | Cible | Statut | Preuve |\n|---|---|---|---|---|---|---|---|---|---|---|\n| A01 | {{action_1}} | {{priorite_1}} | {{responsable_1}} | {{debut_1}} | {{echeance_1}} | {{budget_1}} | {{kpi_1}} | {{cible_1}} | {{statut_1}} | {{preuve_1}} |\n| A02 | {{action_2}} | {{priorite_2}} | {{responsable_2}} | {{debut_2}} | {{echeance_2}} | {{budget_2}} | {{kpi_2}} | {{cible_2}} | {{statut_2}} | {{preuve_2}} |\n| A03 | {{action_3}} | {{priorite_3}} | {{responsable_3}} | {{debut_3}} | {{echeance_3}} | {{budget_3}} | {{kpi_3}} | {{cible_3}} | {{statut_3}} | {{preuve_3}} |\n\n## 12. Risques et dépendances\n{{risques_dependances}}\n\n## 13. Gouvernance de suivi\n- Instance : {{instance}}\n- Fréquence : {{frequence}}\n- Escalade : {{regle_escalade}}\n\n## 14. Ressources et moyens\n{{ressources_moyens}}\n\n## 15. Communication et mobilisation\n{{communication_politique}}\n\n## 16. Preuves et livrables attendus\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 17. Bilan et amélioration continue\n{{bilan}}\n\n{{modalites_revue}}\n\n## Validation\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Commentaires : {{commentaires_validation}}`;}

function register(s:SourceCatalogItem){return`${identity(s)}\n\n${summary}\n\n## 1. Objet du registre / tableau de pilotage\n{{objet}}\n\n## 2. Périmètre\n{{perimetre}}\n\n## 3. Règles de gestion\n{{regles_operationnelles}}\n\n## 4. Critères de classement, seuils et responsabilités\n{{criteres_notation}}\n\n${domainBlock(s,5)}\n\n## 11. Données à enregistrer\n| Référence | Sujet / élément | Catégorie | Responsable | Date | Statut | Niveau de risque / priorité | Action attendue | Preuve / source |\n|---|---|---|---|---|---|---|---|---|\n| {{reference_1}} | {{element_1}} | {{categorie_1}} | {{responsable_1}} | {{date_1}} | {{statut_1}} | {{niveau_1}} | {{action_1}} | {{preuve_1}} |\n| {{reference_2}} | {{element_2}} | {{categorie_2}} | {{responsable_2}} | {{date_2}} | {{statut_2}} | {{niveau_2}} | {{action_2}} | {{preuve_2}} |\n| {{reference_3}} | {{element_3}} | {{categorie_3}} | {{responsable_3}} | {{date_3}} | {{statut_3}} | {{niveau_3}} | {{action_3}} | {{preuve_3}} |\n\n## 12. Modalités de mise à jour\n{{modalites_mise_a_jour}}\n\n## 13. Contrôle de la qualité des données\n{{controle_donnees}}\n\n## 14. Indicateurs issus du registre\n- {{kpi_1}}\n- {{kpi_2}}\n- {{kpi_3}}\n\n## 15. Archivage et traçabilité\n{{modalites_archivage}}\n\n## 16. Revue et amélioration\n{{modalites_revue}}\n\n## Validation\n- Propriétaire : {{role_pilote}}\n- Validateur : {{validateur}}\n- Date : {{date_validation}}`;}

function assessment(s:SourceCatalogItem){return`${identity(s)}\n\n${summary}\n\n## 1. Objectif de l’évaluation\n{{objet}}\n\n## 2. Périmètre et méthode\n{{perimetre}}\n\n{{methode_evaluation}}\n\n## 3. Sources et données utilisées\n{{sources_donnees}}\n\n## 4. Critères d’analyse et niveau attendu\n{{criteres_notation}}\n\n${domainBlock(s,5)}\n\n## 11. Grille d’évaluation\n| Critère | Question / test | Méthode | Niveau attendu | Résultat | Preuve |\n|---|---|---|---|---|---|\n| {{critere_1}} | {{question_1}} | {{methode_1}} | {{niveau_attendu_1}} | {{resultat_1}} | {{preuve_1}} |\n| {{critere_2}} | {{question_2}} | {{methode_2}} | {{niveau_attendu_2}} | {{resultat_2}} | {{preuve_2}} |\n| {{critere_3}} | {{question_3}} | {{methode_3}} | {{niveau_attendu_3}} | {{resultat_3}} | {{preuve_3}} |\n\n## 12. Constats principaux et points forts\n{{constats_principaux}}\n\n{{points_forts}}\n\n## 13. Écarts, risques et points de vigilance\n{{risques_impacts}}\n\n## 14. Priorisation\n{{priorisation}}\n\n## 15. Recommandations et actions\n1. {{action_1}}\n2. {{action_2}}\n3. {{action_3}}\n\n## 16. Responsabilités, échéances et preuves\n{{responsabilites_echeances}}\n\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 17. Revue de l’analyse\n{{modalites_revue}}\n\n## Validation\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Commentaires : {{commentaires_validation}}`;}

function report(s:SourceCatalogItem){return`${identity(s)}\n\n${summary}\n\n## 1. Objet et contexte\n{{objet}}\n\n{{enjeux}}\n\n## 2. Périmètre et période couverte\n{{perimetre}}\n\n{{periode}}\n\n## 3. Méthode et sources\n{{methode_evaluation}}\n\n{{sources_donnees}}\n\n## 4. Résultats clés\n{{resultats_cles}}\n\n${domainBlock(s,5)}\n\n## 11. Analyse détaillée\n{{contenu_principal}}\n\n## 12. Indicateurs\n| Indicateur | Valeur | Cible / référence | Évolution | Commentaire |\n|---|---|---|---|---|\n| {{kpi_1}} | {{valeur_1}} | {{cible_1}} | {{evolution_1}} | {{commentaire_1}} |\n| {{kpi_2}} | {{valeur_2}} | {{cible_2}} | {{evolution_2}} | {{commentaire_2}} |\n| {{kpi_3}} | {{valeur_3}} | {{cible_3}} | {{evolution_3}} | {{commentaire_3}} |\n\n## 13. Écarts, risques et enseignements\n{{risques_impacts}}\n\n## 14. Actions décidées\n1. {{action_1}}\n2. {{action_2}}\n3. {{action_3}}\n\n## 15. Responsables et prochaines échéances\n{{responsabilites_echeances}}\n\n## 16. Preuves, annexes et traçabilité\n- {{preuve_1}}\n- {{preuve_2}}\n- {{preuve_3}}\n\n{{modalites_archivage}}\n\n## 17. Revue et amélioration\n{{modalites_revue}}\n\n## Validation / diffusion\n- Validateur : {{validateur}}\n- Destinataires : {{destinataires}}\n- Date : {{date_validation}}`;}

function proof(s:SourceCatalogItem){return`${identity(s)}\n\n## Synthèse exécutive de la preuve\n- Preuve originale : {{preuve_1}}\n- Sujet démontré : {{objet}}\n- Périmètre : {{perimetre}}\n- Période : {{periode}}\n- Responsable : {{responsable}}\n- Statut : {{statut_validation}}\n\n## 1. Objet et finalité de la fiche\nCette fiche référence, contextualise et qualifie une pièce existante. Elle ne remplace pas le document original.\n\n{{objet}}\n\n## 2. Description du document original\n{{preuve_originale}}\n\n## 3. Périmètre couvert\n{{perimetre_preuve}}\n\n## 4. Émetteur, date et période de validité\n{{emetteur_validite}}\n\n## 5. Ce que la preuve démontre réellement\n{{demonstration_preuve}}\n\n## 6. Limites, exclusions et réserves\n{{limites_reserves}}\n\n## 7. Vérification et cohérence\n{{verification_renouvellement}}\n\n## 8. Source, origine et traçabilité\n{{source_preuve}}\n\n## 9. Contrôles effectués\n{{controles_preuve}}\n\n## 10. Documents liés\n- {{preuve_2}}\n- {{preuve_3}}\n\n## 11. Archivage et durée de conservation\n{{modalites_archivage}}\n\n## 12. Risques en cas d’expiration ou d’invalidité\n{{risques_impacts}}\n\n## 13. Action de renouvellement / mise à jour\n{{action_1}}\n\n## 14. Prochaine vérification\n{{date_prochaine_revue}}\n\n## Validation\n- Validateur : {{validateur}}\n- Date : {{date_validation}}\n- Commentaires : {{commentaires_validation}}`;}

export function buildEnrichedCatalogTemplate(source:SourceCatalogItem):MsdgCatalogTemplate{
 const layout=layoutFor(source.type);
 const markdown=source.model==='FICHE DE PREUVE V3'||layout==='PROOF'?proof(source):layout==='ACTION_PLAN'?actionPlan(source):layout==='REGISTER'?register(source):layout==='ASSESSMENT'?assessment(source):layout==='REPORT'?report(source):policy(source);
 return{id:source.id,title:source.title,category:source.category,type:source.type,priority:source.priority,frameworks:[],frequency:'Selon contexte',layout,sourcePath:`catalogue-source/${source.id}`,description:`Document complet et personnalisable : synthèse exécutive, développement métier approfondi, gouvernance, indicateurs, preuves, gestion des écarts, validation et amélioration continue.`,markdown};
}
