export type Resource={slug:string;category:string;title:string;summary:string;why:string;steps:string[];proof:string;level:'Essentiel'|'Approfondir';minutes:number;pillar?:string};
export const resources:Resource[]=[
{slug:'comprendre-rse',category:'Comprendre la RSE',title:'Comprendre la RSE',summary:'Situer la responsabilité sociétale dans les décisions et impacts de l’entreprise.',why:'Une définition commune permet de passer du sujet général à des décisions concrètes.',steps:['Identifier les principaux impacts de l’activité','Relier ces impacts aux enjeux économiques, sociaux et environnementaux','Choisir les sujets sur lesquels l’entreprise peut réellement agir'],proof:'Note de cadrage RSE',level:'Essentiel',minutes:5},
{slug:'cadre-rse',category:'Comprendre la RSE',title:'Repérer le cadre réglementaire RSE',summary:'Distinguer obligations, référentiels et démarches volontaires utiles à votre PME.',why:'Toutes les entreprises ne sont pas soumises aux mêmes exigences : il faut d’abord identifier celles qui vous concernent.',steps:['Lister taille, activité et marchés de l’entreprise','Recenser les demandes réglementaires et contractuelles','Créer une veille simple sur les exigences pertinentes'],proof:'Registre des exigences RSE',level:'Essentiel',minutes:7},
{slug:'entreprise-mission',category:'Comprendre la RSE',title:'Comprendre l’entreprise à mission',summary:'Comprendre raison d’être, objectifs sociaux et environnementaux et gouvernance de mission.',why:'Le statut peut structurer un engagement stratégique, mais ne constitue pas un passage obligé pour mener une démarche RSE.',steps:['Clarifier la raison d’être','Formuler des objectifs cohérents avec l’activité','Évaluer l’intérêt d’inscrire ces engagements dans les statuts'],proof:'Projet de raison d’être et objectifs',level:'Approfondir',minutes:8},
{slug:'gouvernance-rse',category:'Piloter sa démarche',title:'Installer une gouvernance RSE',summary:'Définir qui décide, qui pilote et comment les progrès sont suivis.',why:'Sans responsabilité claire ni rituel de pilotage, les actions RSE restent souvent dispersées.',steps:['Nommer un pilote','Définir les responsabilités','Installer une revue RSE périodique'],proof:'Lettre de mission + tableau de pilotage',level:'Essentiel',minutes:6,pillar:'Stratégie & gouvernance'},
{slug:'enjeux-rse',category:'Piloter sa démarche',title:'Identifier ses enjeux RSE',summary:'Repérer les impacts, risques et opportunités réellement significatifs pour l’entreprise.',why:'Une PME gagne à concentrer ses moyens sur quelques enjeux matériels plutôt qu’à tout traiter simultanément.',steps:['Cartographier activités et chaîne de valeur','Identifier impacts, risques et opportunités','Hiérarchiser les sujets selon importance et capacité d’action'],proof:'Cartographie des enjeux',level:'Essentiel',minutes:8},
{slug:'parties-prenantes',category:'Piloter sa démarche',title:'Dialoguer avec ses parties prenantes',summary:'Identifier les acteurs importants et organiser un dialogue adapté.',why:'Clients, collaborateurs, fournisseurs, financeurs et acteurs locaux peuvent faire émerger des attentes invisibles en interne.',steps:['Lister les parties prenantes','Évaluer influence et attentes','Choisir une modalité de dialogue adaptée'],proof:'Cartographie parties prenantes',level:'Essentiel',minutes:7,pillar:'Ancrage territorial'},
{slug:'criteres-esg',category:'Clients & reporting',title:'Comprendre les critères ESG',summary:'Comprendre comment environnement, social et gouvernance structurent l’évaluation extra-financière.',why:'Les critères ESG influencent de plus en plus les demandes des clients, financeurs et donneurs d’ordre.',steps:['Repérer les critères pertinents pour votre activité','Identifier les données déjà disponibles','Organiser les preuves associées'],proof:'Matrice ESG',level:'Essentiel',minutes:6,pillar:'Clients & marché'},
{slug:'csrd',category:'Clients & reporting',title:'Comprendre la CSRD et son effet sur les PME',summary:'Comprendre le reporting de durabilité et surtout ses effets indirects dans les chaînes de valeur.',why:'Même hors champ direct, une PME peut recevoir des demandes d’informations de clients soumis à des obligations de reporting.',steps:['Identifier les grands clients concernés','Recenser leurs questionnaires et clauses','Préparer un socle de données réutilisable'],proof:'Matrice des demandes clients',level:'Approfondir',minutes:8,pillar:'Clients & marché'},
{slug:'esrs',category:'Clients & reporting',title:'Comprendre les ESRS',summary:'Découvrir la logique des standards européens de reporting de durabilité.',why:'Connaître leur structure aide à comprendre la provenance de nombreuses demandes adressées par les grands donneurs d’ordre.',steps:['Distinguer informations générales et thématiques','Repérer les thèmes pertinents','Faire le lien avec vos données existantes'],proof:'Table de correspondance enjeux/données',level:'Approfondir',minutes:8},
{slug:'vsme',category:'Clients & reporting',title:'Découvrir le standard VSME',summary:'Structurer volontairement des informations de durabilité dans un format proportionné aux PME.',why:'Un cadre volontaire peut éviter de reconstruire une réponse différente à chaque demande client ou financière.',steps:['Identifier les informations disponibles','Constituer un socle d’indicateurs','Mettre à jour les données périodiquement'],proof:'Dossier VSME interne',level:'Approfondir',minutes:8,pillar:'Clients & marché'},
{slug:'reporting-rse',category:'Clients & reporting',title:'Construire une synthèse RSE utile',summary:'Transformer actions, indicateurs et preuves en information lisible et réutilisable.',why:'Une synthèse courte et factuelle facilite les réponses aux clients, partenaires et collaborateurs.',steps:['Sélectionner les enjeux prioritaires','Associer indicateurs, actions et résultats','Relier chaque affirmation à une preuve'],proof:'Synthèse RSE annuelle',level:'Essentiel',minutes:7,pillar:'Clients & marché'},
{slug:'engager-collaborateurs',category:'Social',title:'Engager les collaborateurs',summary:'Faire de la démarche RSE un sujet concret de management et de participation.',why:'Les actions sont plus durables lorsque les équipes comprennent les objectifs et peuvent contribuer.',steps:['Expliquer les priorités','Recueillir des propositions','Partager régulièrement les progrès'],proof:'Compte rendu de sensibilisation',level:'Essentiel',minutes:6,pillar:'Social & conditions de travail'},
{slug:'vigilance-fournisseurs',category:'Achats responsables',title:'Structurer la vigilance fournisseurs',summary:'Identifier les risques sociaux, environnementaux et éthiques de la chaîne d’approvisionnement.',why:'Les achats concentrent souvent une part importante des impacts et des exigences clients.',steps:['Segmenter les fournisseurs','Identifier les familles à risque','Définir les contrôles et actions adaptés'],proof:'Cartographie des risques fournisseurs',level:'Approfondir',minutes:9,pillar:'Achats responsables'},
{slug:'carbone',category:'Environnement',title:'Comprendre et réduire son empreinte carbone',summary:'Comprendre les émissions directes, liées à l’énergie et celles de la chaîne de valeur.',why:'Une première cartographie permet d’éviter de concentrer les efforts sur des postes secondaires.',steps:['Définir le périmètre','Collecter les principales données d’activité','Identifier les postes majeurs puis un plan de réduction'],proof:'Bilan ou estimation carbone + plan d’action',level:'Essentiel',minutes:9,pillar:'Environnement'},
{slug:'marketing-responsable',category:'Business responsable',title:'Rendre son marketing plus responsable',summary:'Aligner les messages commerciaux avec les impacts réels et les preuves disponibles.',why:'Une communication crédible doit éviter les allégations vagues et rester démontrable.',steps:['Auditer les principales allégations','Associer chaque message à une preuve','Corriger les formulations non démontrables'],proof:'Grille de validation des allégations',level:'Essentiel',minutes:6,pillar:'Clients & marché'},
{slug:'logistique-responsable',category:'Business responsable',title:'Agir sur la logistique et la distribution',summary:'Réduire les impacts liés aux flux, transports, emballages et opérations de distribution.',why:'Les flux logistiques combinent enjeux carbone, coûts, conditions de travail et qualité de service.',steps:['Cartographier les flux','Identifier les postes d’impact','Tester une amélioration mesurable'],proof:'Plan d’amélioration logistique',level:'Essentiel',minutes:7,pillar:'Environnement'},
{slug:'economie-circulaire',category:'Économie circulaire',title:'Passer vers des modèles plus circulaires',summary:'Réduire l’usage de ressources et prolonger la valeur des produits et matières.',why:'Écoconception, réemploi, réparation et recyclage peuvent réduire les impacts tout en ouvrant de nouveaux leviers économiques.',steps:['Cartographier matières et déchets','Rechercher les boucles de réemploi ou prolongation','Choisir une expérimentation prioritaire'],proof:'Plan d’action économie circulaire',level:'Essentiel',minutes:8,pillar:'Environnement'}];
export const categories=[...new Set(resources.map(r=>r.category))];
