export type NoteCadrageField={section:string;label:string;placeholder:string;rows?:number};

export const noteCadrageFields:NoteCadrageField[]=[
{section:'Informations du document',label:'Référent RSE',placeholder:'Nom / fonction'},{section:'Informations du document',label:'Version',placeholder:'V1 – Brouillon / Validée'},
{section:'2. L’entreprise en quelques lignes',label:'Activité principale',placeholder:'Décrivez l’activité principale de l’entreprise.'},{section:'2. L’entreprise en quelques lignes',label:'Produits / services',placeholder:'Principaux produits ou services.'},{section:'2. L’entreprise en quelques lignes',label:'Clients / marchés principaux',placeholder:'Principaux clients, segments ou marchés.'},{section:'2. L’entreprise en quelques lignes',label:'Fournisseurs / partenaires clés',placeholder:'Fournisseurs et partenaires structurants.'},{section:'2. L’entreprise en quelques lignes',label:'Zone géographique d’activité',placeholder:'Territoires, régions ou pays couverts.'},{section:'2. L’entreprise en quelques lignes',label:'Principales ressources nécessaires',placeholder:'Ressources humaines, matières, énergie, équipements, données…'},{section:'2. L’entreprise en quelques lignes',label:'Création de valeur',placeholder:'Nous créons de la valeur grâce à…'},{section:'2. L’entreprise en quelques lignes',label:'Dépendances clés',placeholder:'Nous dépendons notamment de…'},{section:'2. L’entreprise en quelques lignes',label:'Facteurs de vulnérabilité',placeholder:'Nos principaux facteurs de vulnérabilité sont…'},
{section:'3. Pourquoi engager une démarche RSE ?',label:'Motivations principales',placeholder:'Une motivation par ligne : attentes clients, réglementation, coûts, collaborateurs…',rows:5},{section:'3. Pourquoi engager une démarche RSE ?',label:'Motivation principale',placeholder:'La motivation prioritaire qui justifie la démarche.'},
{section:'4. Parties prenantes principales',label:'Parties prenantes',placeholder:'Une ligne par acteur : Partie prenante | Attentes | Influence | Impact de l’entreprise\nEx. Clients | Preuves RSE | Fort | Moyen',rows:8},
{section:'5. État initial de la démarche RSE',label:'Pratiques RSE existantes',placeholder:'Une pratique existante par ligne.',rows:5},{section:'5. État initial de la démarche RSE',label:'Actions déjà engagées',placeholder:'Une action par ligne.',rows:5},{section:'5. État initial de la démarche RSE',label:'Maturité par domaine',placeholder:'Domaine | Niveau de 1 à 5\nEx. Gouvernance RSE | 2',rows:8},
{section:'6. Impacts positifs et négatifs',label:'Environnement - impacts positifs',placeholder:'Un impact positif par ligne.',rows:4},{section:'6. Impacts positifs et négatifs',label:'Environnement - points de vigilance',placeholder:'Un impact négatif ou point de vigilance par ligne.',rows:4},{section:'6. Impacts positifs et négatifs',label:'Social - impacts positifs',placeholder:'Un impact positif par ligne.',rows:4},{section:'6. Impacts positifs et négatifs',label:'Social - points de vigilance',placeholder:'Un point de vigilance par ligne.',rows:4},{section:'6. Impacts positifs et négatifs',label:'Économie et territoire - impacts positifs',placeholder:'Un impact positif par ligne.',rows:4},{section:'6. Impacts positifs et négatifs',label:'Économie et territoire - points de vigilance',placeholder:'Un point de vigilance par ligne.',rows:4},{section:'6. Impacts positifs et négatifs',label:'Gouvernance - points forts',placeholder:'Un point fort par ligne.',rows:4},{section:'6. Impacts positifs et négatifs',label:'Gouvernance - points de vigilance',placeholder:'Un point de vigilance par ligne.',rows:4},
{section:'7. Risques et opportunités RSE',label:'Principaux risques',placeholder:'Risque | Probabilité 1-5 | Impact 1-5 | Vigilance | Réponse envisagée',rows:6},{section:'7. Risques et opportunités RSE',label:'Principales opportunités',placeholder:'Opportunité | Potentiel 1-5 | Faisabilité 1-5 | Priorité | Première piste',rows:6},
{section:'8. Analyse de matérialité simplifiée',label:'Analyse de matérialité',placeholder:'Enjeu | Impact /5 | Importance /5 | Score /25 | Priorité',rows:7},
{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 1 - enjeu',placeholder:'Nom de l’enjeu'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 1 - pourquoi',placeholder:'Pourquoi cet enjeu est prioritaire ?'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 1 - situation actuelle',placeholder:'Situation actuelle'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 1 - résultat recherché',placeholder:'Résultat recherché'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 2 - enjeu',placeholder:'Nom de l’enjeu'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 2 - pourquoi',placeholder:'Pourquoi cet enjeu est prioritaire ?'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 2 - situation actuelle',placeholder:'Situation actuelle'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 2 - résultat recherché',placeholder:'Résultat recherché'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 3 - enjeu',placeholder:'Nom de l’enjeu'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 3 - pourquoi',placeholder:'Pourquoi cet enjeu est prioritaire ?'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 3 - situation actuelle',placeholder:'Situation actuelle'},{section:'9. Nos enjeux RSE prioritaires',label:'Priorité 3 - résultat recherché',placeholder:'Résultat recherché'},
{section:'10. Arbitrage des priorités',label:'Matrice de décision',placeholder:'Action / enjeu | Impact 1-5 | Urgence 1-5 | Faisabilité 1-5 | Ressources | Décision',rows:6},
{section:'11. Ambition RSE à 12 mois',label:'Ambition à 12 mois',placeholder:'Dans les 12 prochains mois, l’entreprise souhaite…',rows:4},{section:'11. Ambition RSE à 12 mois',label:'Résultats attendus à 12 mois',placeholder:'Un résultat attendu par ligne.',rows:6},
{section:'12. Indicateurs de départ',label:'Indicateurs de départ',placeholder:'Indicateur | Situation actuelle | Objectif à 12 mois',rows:8},
{section:'13. Objectifs à 12 mois',label:'Objectifs à 12 mois',placeholder:'Axe | Objectif | KPI | Situation initiale | Cible 12 mois | Responsable',rows:8},
{section:'14. Périmètre retenu',label:'Périmètre de la démarche',placeholder:'Éléments inclus dans le périmètre, un par ligne.',rows:5},{section:'14. Périmètre retenu',label:'Hors périmètre pour le moment',placeholder:'Éléments temporairement hors périmètre.',rows:4},
{section:'15. Gouvernance de la démarche',label:'Sponsor de la démarche',placeholder:'Nom / fonction'},{section:'15. Gouvernance de la démarche',label:'Référent de la démarche',placeholder:'Nom / fonction'},{section:'15. Gouvernance de la démarche',label:'Personnes associées',placeholder:'Une personne / fonction par ligne.',rows:5},{section:'15. Gouvernance de la démarche',label:'Modalités de pilotage',placeholder:'Point mensuel, trimestriel, revue semestrielle…',rows:4},
{section:'16. Feuille de route des 90 prochains jours',label:'Action 1 - action',placeholder:'Quick win à engager'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 1 - enjeu',placeholder:'Enjeu concerné'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 1 - responsable',placeholder:'Nom'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 1 - échéance',placeholder:'Date'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 1 - KPI',placeholder:'Indicateur de réussite'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 2 - action',placeholder:'Action de structuration'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 2 - enjeu',placeholder:'Enjeu concerné'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 2 - responsable',placeholder:'Nom'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 2 - échéance',placeholder:'Date'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 2 - KPI',placeholder:'Indicateur de réussite'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 3 - action',placeholder:'Action de mobilisation'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 3 - enjeu',placeholder:'Enjeu concerné'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 3 - responsable',placeholder:'Nom'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 3 - échéance',placeholder:'Date'},{section:'16. Feuille de route des 90 prochains jours',label:'Action 3 - KPI',placeholder:'Indicateur de réussite'},
{section:'18. Décisions de la direction',label:'Décisions de la direction',placeholder:'Une décision validée par ligne.',rows:6},{section:'18. Décisions de la direction',label:'Points nécessitant un arbitrage',placeholder:'Décisions ou arbitrages encore nécessaires.',rows:4},
{section:'Validation',label:'Validation - nom',placeholder:'Nom du représentant de la direction'},{section:'Validation',label:'Validation - fonction',placeholder:'Fonction'},{section:'Validation',label:'Validation - date',placeholder:'JJ/MM/AAAA'},{section:'Validation',label:'Validation - statut',placeholder:'Validé / Validé sous réserve / À compléter'},{section:'Validation',label:'Validation - commentaires',placeholder:'Commentaires / décisions complémentaires',rows:4}
];
