export type TemplateField={label:string;placeholder:string};
export type ActionTemplate={slug:string;title:string;objective:string;fields:TemplateField[];deliverable:string};
export const templates:ActionTemplate[]=[
{slug:'comprendre-rse',title:'Note de cadrage RSE',objective:'Transformer la RSE en périmètre de travail concret.',fields:[{label:'Activités principales',placeholder:'Nos activités principales sont…'},{label:'Impacts positifs et négatifs',placeholder:'Nos principaux impacts sont…'},{label:'Enjeux prioritaires',placeholder:'Les sujets à traiter en priorité sont…'},{label:'Ambition à 12 mois',placeholder:'Dans 12 mois, nous voulons…'}],deliverable:'Une note de cadrage RSE validée par la direction.'},
{slug:'cadre-rse',title:'Registre des exigences RSE',objective:'Identifier les exigences applicables ou demandées à l’entreprise.',fields:[{label:'Exigence',placeholder:'Loi, règlement, norme, demande client…'},{label:'Origine',placeholder:'Client, réglementation, financeur…'},{label:'Applicabilité',placeholder:'Obligatoire / contractuelle / volontaire'},{label:'Action nécessaire',placeholder:'Ce que nous devons mettre en place…'},{label:'Responsable et échéance',placeholder:'Nom / date'}],deliverable:'Un registre des exigences à suivre et à mettre à jour.'},
{slug:'entreprise-mission',title:'Canevas raison d’être & mission',objective:'Tester la pertinence d’une raison d’être et d’objectifs de mission.',fields:[{label:'Utilité de l’entreprise',placeholder:'Notre entreprise contribue à…'},{label:'Parties prenantes bénéficiaires',placeholder:'Clients, salariés, territoire…'},{label:'Objectifs sociaux/environnementaux',placeholder:'Nous nous engageons à…'},{label:'Indicateurs de suivi',placeholder:'Nous mesurerons…'}],deliverable:'Un projet de raison d’être et d’objectifs à arbitrer.'},
{slug:'gouvernance-rse',title:'Fiche de gouvernance RSE',objective:'Rendre explicites responsabilités, décisions et rythme de pilotage.',fields:[{label:'Sponsor direction',placeholder:'Nom / fonction'},{label:'Pilote RSE',placeholder:'Nom / fonction'},{label:'Contributeurs',placeholder:'Services / personnes'},{label:'Rituels',placeholder:'Réunion mensuelle, revue trimestrielle…'},{label:'Décisions réservées à la direction',placeholder:'Budget, objectifs, engagements…'}],deliverable:'Une gouvernance RSE simple et opérationnelle.'},
{slug:'enjeux-rse',title:'Matrice de priorisation des enjeux',objective:'Hiérarchiser les sujets selon importance et capacité d’action.',fields:[{label:'Enjeu',placeholder:'Énergie, achats, QVT…'},{label:'Impact entreprise/société',placeholder:'Faible / moyen / fort'},{label:'Attente parties prenantes',placeholder:'Faible / moyenne / forte'},{label:'Urgence',placeholder:'1 à 3'},{label:'Capacité d’action',placeholder:'1 à 3'},{label:'Décision',placeholder:'Prioritaire / à suivre / secondaire'}],deliverable:'Une liste courte d’enjeux réellement prioritaires.'},
{slug:'parties-prenantes',title:'Cartographie des parties prenantes',objective:'Organiser un dialogue proportionné avec les acteurs importants.',fields:[{label:'Partie prenante',placeholder:'Clients, salariés, fournisseurs…'},{label:'Attentes',placeholder:'Ce qu’elle attend de nous…'},{label:'Influence',placeholder:'Faible / moyenne / forte'},{label:'Impact de nos activités',placeholder:'Faible / moyen / fort'},{label:'Mode de dialogue',placeholder:'Entretien, questionnaire, réunion…'},{label:'Fréquence',placeholder:'Mensuelle / annuelle…'}],deliverable:'Une cartographie assortie d’un plan de dialogue.'},
{slug:'criteres-esg',title:'Matrice ESG',objective:'Structurer les données environnementales, sociales et de gouvernance utiles.',fields:[{label:'Pilier ESG',placeholder:'E / S / G'},{label:'Sujet',placeholder:'Énergie, sécurité, éthique…'},{label:'Indicateur',placeholder:'kWh, fréquence accidents…'},{label:'Donnée disponible',placeholder:'Oui / non / partiellement'},{label:'Source / preuve',placeholder:'Facture, registre, procédure…'},{label:'Responsable',placeholder:'Nom / service'}],deliverable:'Un socle ESG documenté et réutilisable.'},
{slug:'csrd',title:'Matrice des demandes clients',objective:'Anticiper les demandes RSE transmises par les donneurs d’ordre.',fields:[{label:'Client',placeholder:'Nom du client'},{label:'Demande',placeholder:'Questionnaire, données carbone, charte…'},{label:'Fréquence',placeholder:'Appel d’offres / annuelle…'},{label:'Donnée disponible',placeholder:'Oui / non'},{label:'Preuve associée',placeholder:'Document ou indicateur'},{label:'Action manquante',placeholder:'À produire / mettre à jour…'}],deliverable:'Une base unique pour répondre plus vite aux clients.'},
{slug:'esrs',title:'Table de correspondance enjeux / données',objective:'Comprendre quelles données internes répondent aux grands thèmes de durabilité.',fields:[{label:'Thème',placeholder:'Climat, personnel, conduite des affaires…'},{label:'Enjeu pour l’entreprise',placeholder:'Pourquoi ce thème nous concerne…'},{label:'Donnée disponible',placeholder:'Indicateur / information qualitative'},{label:'Source',placeholder:'RH, achats, comptabilité…'},{label:'Manque identifié',placeholder:'Donnée à créer ou fiabiliser'}],deliverable:'Une cartographie simple des informations de durabilité.'},
{slug:'vsme',title:'Dossier VSME interne',objective:'Constituer progressivement un socle PME de données de durabilité.',fields:[{label:'Information',placeholder:'Politique, indicateur, action…'},{label:'Valeur / réponse',placeholder:'Donnée actuelle'},{label:'Période',placeholder:'Année / date'},{label:'Source',placeholder:'Document / système'},{label:'Preuve',placeholder:'Fichier à conserver'},{label:'Statut',placeholder:'Disponible / à compléter'}],deliverable:'Un dossier de données réutilisable pour clients et financeurs.'},
{slug:'reporting-rse',title:'Trame de synthèse RSE',objective:'Présenter les engagements et résultats sans allégation non démontrée.',fields:[{label:'Priorité',placeholder:'Notre priorité est…'},{label:'Objectif',placeholder:'Nous visons…'},{label:'Action réalisée',placeholder:'Nous avons mis en place…'},{label:'Indicateur / résultat',placeholder:'Résultat mesuré…'},{label:'Preuve',placeholder:'Document associé'},{label:'Prochaine étape',placeholder:'Nous allons…'}],deliverable:'Une synthèse RSE courte, factuelle et démontrable.'},
{slug:'engager-collaborateurs',title:'Plan d’engagement collaborateurs',objective:'Faire participer les équipes aux priorités RSE.',fields:[{label:'Priorité à partager',placeholder:'Sujet RSE'},{label:'Message clé',placeholder:'Pourquoi cela compte…'},{label:'Mode de participation',placeholder:'Atelier, idée, challenge…'},{label:'Responsable',placeholder:'Nom'},{label:'Date',placeholder:'Échéance'},{label:'Retour / décision',placeholder:'Ce qui a été retenu…'}],deliverable:'Un plan d’animation et une trace des contributions.'},
{slug:'vigilance-fournisseurs',title:'Cartographie des risques fournisseurs',objective:'Prioriser la vigilance là où le risque achat est le plus significatif.',fields:[{label:'Fournisseur / famille',placeholder:'Nom ou catégorie'},{label:'Pays / origine',placeholder:'Zone concernée'},{label:'Risque social',placeholder:'Faible / moyen / fort'},{label:'Risque environnemental',placeholder:'Faible / moyen / fort'},{label:'Risque éthique',placeholder:'Faible / moyen / fort'},{label:'Contrôle / action',placeholder:'Questionnaire, audit, clause…'}],deliverable:'Une cartographie permettant de cibler les actions fournisseurs.'},
{slug:'carbone',title:'Plan de collecte carbone',objective:'Identifier les principales sources d’émissions avant de définir les réductions.',fields:[{label:'Poste d’émission',placeholder:'Énergie, déplacements, achats…'},{label:'Donnée d’activité',placeholder:'kWh, km, € ou quantité'},{label:'Source',placeholder:'Facture, ERP, relevé…'},{label:'Responsable donnée',placeholder:'Nom / service'},{label:'Importance estimée',placeholder:'Faible / moyenne / forte'},{label:'Piste de réduction',placeholder:'Action envisageable'}],deliverable:'Une première cartographie carbone et des leviers de réduction.'},
{slug:'marketing-responsable',title:'Grille de validation des allégations',objective:'Sécuriser les messages RSE avant publication.',fields:[{label:'Allégation',placeholder:'Message utilisé ou envisagé'},{label:'Fait démontré',placeholder:'Ce que nous pouvons réellement affirmer'},{label:'Preuve',placeholder:'Étude, indicateur, certificat…'},{label:'Périmètre',placeholder:'Produit / entreprise / période'},{label:'Risque d’ambiguïté',placeholder:'Faible / moyen / fort'},{label:'Formulation validée',placeholder:'Version finale'}],deliverable:'Une validation traçable des communications RSE.'},
{slug:'logistique-responsable',title:'Plan d’amélioration logistique',objective:'Choisir des améliorations mesurables sur les flux.',fields:[{label:'Flux',placeholder:'Transport amont, livraison…'},{label:'Impact actuel',placeholder:'Coût, CO2, emballage, sécurité…'},{label:'Indicateur de départ',placeholder:'Valeur actuelle'},{label:'Action testée',placeholder:'Mutualisation, optimisation…'},{label:'Objectif',placeholder:'Résultat attendu'},{label:'Mesure après test',placeholder:'Résultat obtenu'}],deliverable:'Un plan d’expérimentation logistique mesurable.'},
{slug:'economie-circulaire',title:'Canevas d’expérimentation circulaire',objective:'Passer d’une idée circulaire à un test concret.',fields:[{label:'Produit / matière',placeholder:'Flux ciblé'},{label:'Problème actuel',placeholder:'Déchet, durée de vie, consommation…'},{label:'Boucle envisagée',placeholder:'Réemploi, réparation, recyclage…'},{label:'Partenaire nécessaire',placeholder:'Client, fournisseur, recycleur…'},{label:'Test à réaliser',placeholder:'Expérimentation simple'},{label:'Indicateur de succès',placeholder:'kg évités, durée de vie, €…'}],deliverable:'Une expérimentation circulaire avec critère de succès.'}
];
export const templateBySlug=(slug:string)=>templates.find(t=>t.slug===slug);
