'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Target,Clock,Gauge,CheckCircle2} from 'lucide-react';
type Result={score:number;sector:string;size:string;maturity:string;priorities:string[]};
const library:Record<string,{title:string;why:string;action:string;time:string;impact:string;proof:string}>={
'Stratégie & gouvernance':{title:'Formaliser vos engagements RSE',why:'Donnez un cap clair à votre démarche et rendez vos engagements lisibles pour vos parties prenantes.',action:'Créer une politique RSE courte et opérationnelle',time:'2 h',impact:'Fort',proof:'Politique RSE validée'},
'Environnement':{title:'Mesurer vos impacts environnementaux',why:'Commencez par quelques données utiles pour cibler les réductions les plus pertinentes.',action:'Sélectionner 3 indicateurs environnementaux',time:'2 h',impact:'Fort',proof:'Tableau de suivi des indicateurs'},
'Social & conditions de travail':{title:'Structurer votre feuille de route sociale',why:'Transformez vos pratiques RH existantes en engagements suivis et démontrables.',action:'Formaliser vos actions sociales prioritaires',time:'2 h',impact:'Fort',proof:'Plan d’action social'},
'Achats responsables':{title:'Structurer vos achats responsables',why:'Réduisez les risques fournisseurs et valorisez vos pratiques auprès de vos clients.',action:'Créer une charte fournisseurs responsables',time:'3 h',impact:'Fort',proof:'Charte fournisseurs'},
'Ancrage territorial':{title:'Valoriser votre contribution locale',why:'Identifiez vos partenariats, emplois et actions locales pour rendre votre impact territorial visible.',action:'Cartographier vos actions et partenaires locaux',time:'1 h',impact:'Moyen',proof:'Cartographie territoriale'},
'Clients & marché':{title:'Préparer vos preuves RSE clients',why:'Centralisez les éléments attendus dans les questionnaires et appels d’offres de vos clients.',action:'Constituer votre dossier de preuves RSE',time:'2 h',impact:'Très fort',proof:'Dossier de preuves client'}
};
const fallback:Result={score:62,sector:'PME',size:'10–49',maturity:'Quelques actions existent',priorities:['Stratégie & gouvernance','Achats responsables','Clients & marché']};
export default function Priorities(){const[result,setResult]=useState<Result>(fallback);useEffect(()=>{try{const saved=localStorage.getItem('fabrique-impact-diagnostic');if(saved)setResult(JSON.parse(saved))}catch{}},[]);return <main className="actionPage"><div className="actionWrap"><Link className="backLink" href="/dashboard/"><ArrowLeft/>Retour au tableau de bord</Link><span className="kicker">MES 3 PRIORITÉS</span><h1>Concentrez-vous sur ce qui compte maintenant.</h1><p className="actionLead">À partir de votre diagnostic, nous avons sélectionné trois sujets à traiter en priorité. L’objectif n’est pas de tout faire : c’est d’avancer dans le bon ordre.</p><div className="priorityFocus">{result.priorities.slice(0,3).map((pillar,i)=>{const p=library[pillar];if(!p)return null;return <article key={pillar}><div className="priorityFocusTop"><span className="priorityRank">{String(i+1).padStart(2,'0')}</span><span className="pill">{i===0?'À démarrer maintenant':'À planifier'}</span></div><span className="actionPillar">{pillar}</span><h2>{p.title}</h2><p>{p.why}</p><div className="priorityWhy"><b>Pourquoi maintenant ?</b><span>Votre diagnostic indique que ce sujet fait partie de vos marges de progression les plus importantes.</span></div><div className="priorityFacts"><span><Gauge/>Impact <b>{p.impact}</b></span><span><Clock/>Effort <b>{p.time}</b></span><span><CheckCircle2/>Preuve <b>{p.proof}</b></span></div><div className="recommendedAction"><Target/><div><small>ACTION RECOMMANDÉE</small><b>{p.action}</b></div></div><Link className="priorityAction" href="/actions/">Passer à l’action <ArrowRight/></Link></article>})}</div><div className="nextStep"><div><span className="kicker">ÉTAPE SUIVANTE</span><h2>Transformez ces priorités en plan d’action 90 jours.</h2></div><Link className="button" href="/actions/">Voir mon plan d’action <ArrowRight/></Link></div></div></main>}
